[build]
  # Build command - navigate to trackbin-app directory and build
  command = "cd trackbin-app && npm install && npm run build"
  
  # Publish directory - where the built files are located
  publish = "trackbin-app/dist"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"

# Client-side routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Configure custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"